<#
.SYNOPSIS
    Generates an interactive, standalone HTML Forensic Report from DFIR collected artifacts.

.DESCRIPTION
    Parses collected CSV files and forensic evidence generated by DFIR-Script.ps1 and granular
    acquisition scripts, generating a standalone, interactive HTML dashboard. Includes metric cards,
    real-time search/filter, sorting, categorized tabs, and automated suspicious indicator highlighting.

.PARAMETER EvidencePath
    The path to the DFIR output directory (e.g. .\DFIR-HOSTNAME-2026-08-21) or evidence ZIP file.
    If omitted, the script automatically searches for the most recent DFIR-* folder in the current directory.

.PARAMETER OutputFile
    Path for the generated HTML report. Defaults to 'DFIR-Report-<Hostname>-<Timestamp>.html'.

.PARAMETER OpenReport
    Automatically opens the generated HTML report in the default web browser upon completion.

.PARAMETER Title
    Custom title for the forensic report.

.EXAMPLE
    .\Generate-DFIRHtmlReport.ps1

.EXAMPLE
    .\Generate-DFIRHtmlReport.ps1 -EvidencePath ".\DFIR-DESKTOP-2026-08-21" -OpenReport

.EXAMPLE
    .\Generate-DFIRHtmlReport.ps1 -EvidencePath ".\DFIR-DESKTOP-2026-08-21.zip" -OutputFile "C:\Reports\Incident-001.html" -OpenReport
#>

[CmdletBinding()]
param (
    [Parameter(Mandatory = $false, Position = 0)]
    [string]$EvidencePath,

    [Parameter(Mandatory = $false)]
    [string]$OutputFile,

    [Parameter(Mandatory = $false)]
    [switch]$OpenReport,

    [Parameter(Mandatory = $false)]
    [string]$Title = "Digital Forensics & Incident Response Report"
)

# 1. Resolve Evidence Directory
$tempExtractDir = $null
if (-not $EvidencePath) {
    # Search locations in priority order: current folder, parent folder, script root, script parent
    $currentLoc = (Get-Location).Path
    $parentLoc = if ($currentLoc) { Split-Path $currentLoc -Parent } else { $null }
    $scriptLoc = $PSScriptRoot
    $scriptParentLoc = if ($PSScriptRoot) { Split-Path $PSScriptRoot -Parent } else { $null }

    $searchLocations = @($currentLoc, $parentLoc, $scriptLoc, $scriptParentLoc) | 
        Where-Object { $_ -and (Test-Path $_) } | Select-Object -Unique

    foreach ($loc in $searchLocations) {
        $latestDir = Get-ChildItem -Path $loc -Directory -Filter "DFIR-*" -ErrorAction SilentlyContinue | 
            Sort-Object LastWriteTime -Descending | Select-Object -First 1

        if ($latestDir) {
            $EvidencePath = $latestDir.FullName
            Write-Host "[+] Auto-detected evidence directory: $EvidencePath" -ForegroundColor Green
            break
        }

        $latestZip = Get-ChildItem -Path $loc -File -Filter "DFIR-*.zip" -ErrorAction SilentlyContinue | 
            Sort-Object LastWriteTime -Descending | Select-Object -First 1

        if ($latestZip) {
            $EvidencePath = $latestZip.FullName
            Write-Host "[+] Auto-detected evidence archive: $EvidencePath" -ForegroundColor Green
            break
        }
    }
}

if (-not $EvidencePath -or -not (Test-Path $EvidencePath)) {
    Write-Error "No evidence directory (DFIR-*) or archive (DFIR-*.zip) found in the current or parent directory. Please specify -EvidencePath <path>"
    return
}

# Handle ZIP extraction if evidence path is a .zip archive
if ((Get-Item $EvidencePath) -is [System.IO.FileInfo] -and $EvidencePath.EndsWith(".zip", [System.StringComparison]::OrdinalIgnoreCase)) {
    Write-Host "[*] Extracting ZIP archive to temporary location..." -ForegroundColor Yellow
    $tempExtractDir = Join-Path $env:TEMP "DFIR_Extract_$(Get-Random)"
    New-Item -Path $tempExtractDir -ItemType Directory -Force | Out-Null
    Expand-Archive -Path $EvidencePath -DestinationPath $tempExtractDir -Force
    $targetDir = $tempExtractDir
} else {
    $targetDir = $EvidencePath
}

# Locate CSV results directory
$csvDir = Join-Path $targetDir "CSV Results (SIEM Import Data)"
if (-not (Test-Path $csvDir)) {
    # Search recursively for CSV folder or .csv files
    $foundCsvDirs = Get-ChildItem -Path $targetDir -Directory -Recurse -Filter "*CSV*" -ErrorAction SilentlyContinue
    if ($foundCsvDirs) {
        $csvDir = $foundCsvDirs[0].FullName
    } else {
        $csvDir = $targetDir
    }
}

Write-Host "[*] Reading CSV evidence from: $csvDir" -ForegroundColor Cyan

# Helper function to read and convert CSV safely
function Import-SafeCsv {
    param([string]$Path)
    if (Test-Path $Path) {
        try {
            $data = Import-Csv -Path $Path -ErrorAction Stop
            return @($data)
        } catch {
            Write-Warning "Could not parse CSV: $Path ($($_.Exception.Message))"
            return @()
        }
    }
    return @()
}

# Helper to escape HTML characters
function Escape-Html {
    param([string]$Text)
    if ([string]::IsNullOrEmpty($Text)) { return "" }
    return [System.Web.HttpUtility]::HtmlEncode($Text)
}

# 2. Ingest Evidence Data
$dataStore = [ordered]@{}

$csvMappings = @(
    @{ Key = "Processes"; File = "Processes.csv"; Category = "Execution"; Title = "Active Processes"; Icon = "fas fa-microchip" },
    @{ Key = "OpenTCP"; File = "OpenTCPConnections.csv"; Category = "Network"; Title = "Open TCP Connections"; Icon = "fas fa-network-wired" },
    @{ Key = "IPConfig"; File = "IPConfiguration.csv"; Category = "Network"; Title = "IP Configuration"; Icon = "fas fa-ethernet" },
    @{ Key = "DNSCache"; File = "DNSCache.csv"; Category = "Network"; Title = "DNS Cache"; Icon = "fas fa-globe" },
    @{ Key = "SMBShares"; File = "SMBShares.csv"; Category = "Network"; Title = "SMB Shares"; Icon = "fas fa-folder-open" },
    @{ Key = "NetworkShares"; File = "NetworkShares.csv"; Category = "Network"; Title = "Mapped Network Shares"; Icon = "fas fa-share-alt" },
    @{ Key = "OfficeConn"; File = "OfficeConnections.csv"; Category = "Network"; Title = "Office Connections"; Icon = "fas fa-cloud" },
    @{ Key = "AutoRun"; File = "AutoRun.csv"; Category = "Persistence"; Title = "AutoRun & Startup Commands"; Icon = "fas fa-bolt" },
    @{ Key = "Win32Run"; File = "Win32RegRunKey.csv"; Category = "Persistence"; Title = "Registry Run Keys (WOW64)"; Icon = "fas fa-key" },
    @{ Key = "ScheduledTasks"; File = "ScheduledTasks.csv"; Category = "Persistence"; Title = "Scheduled Tasks"; Icon = "fas fa-clock" },
    @{ Key = "Services"; File = "RunningServices.csv"; Category = "Persistence"; Title = "Running Services"; Icon = "fas fa-cogs" },
    @{ Key = "Drivers"; File = "Drivers.csv"; Category = "System"; Title = "Installed Drivers"; Icon = "fas fa-hdd" },
    @{ Key = "LocalUsers"; File = "LocalUsers.csv"; Category = "Identity"; Title = "Local Users"; Icon = "fas fa-user" },
    @{ Key = "ActiveUsers"; File = "ActiveUsers.csv"; Category = "Identity"; Title = "Active Logged-On Users"; Icon = "fas fa-user-check" },
    @{ Key = "RDPSessions"; File = "RDPSessions.csv"; Category = "Identity"; Title = "RDP Sessions"; Icon = "fas fa-desktop" },
    @{ Key = "SecurityEvents"; File = "SecurityEvents.csv"; Category = "Security"; Title = "Security Events"; Icon = "fas fa-shield-alt" },
    @{ Key = "DefenderExclusions"; File = "DefenderExclusions.csv"; Category = "Security"; Title = "Defender Exclusions"; Icon = "fas fa-shield-virus" },
    @{ Key = "ShadowCopy"; File = "ShadowCopy.csv"; Category = "System"; Title = "Volume Shadow Copies"; Icon = "fas fa-history" },
    @{ Key = "ConnectedDevices"; File = "ConnectedDevices.csv"; Category = "Hardware"; Title = "Connected PnP / USB Devices"; Icon = "fas fa-usb" },
    @{ Key = "InstalledSoftware"; File = "InstalledSoftware.csv"; Category = "System"; Title = "Installed Applications"; Icon = "fas fa-box" },
    @{ Key = "PSHistory"; File = "PowerShellHistory.csv"; Category = "Execution"; Title = "PowerShell History"; Icon = "fas fa-terminal" }
)

$totalArtifactsCount = 0
$suspiciousIndicators = @()

# Suspicious keywords & patterns for automated triage detection
$suspiciousPatterns = @(
    "powershell.*(-enc|-encodedcommand|downloadstring|iex|invoke-expression|bypass)",
    "cmd\.exe.*/c",
    "certutil.*(-urlcache|-split|-f)",
    "rundll32",
    "regsvr32.*/s.*/u",
    "mshta",
    "wscript|cscript",
    "vssadmin.*delete.*shadows",
    "wmic.*shadowcopy.*delete",
    "whoami|nltest|net1?\s+(user|group|localgroup)",
    "mimikatz|sekurlsa|kerberos|rubeus|bloodhound|sharphound",
    "psexec|paexec|cobaltstrike|sliver",
    "\\temp\\|\\appdata\\local\\temp\\.*\.exe"
)

foreach ($map in $csvMappings) {
    $filePath = Join-Path $csvDir $map.File
    if (Test-Path $filePath) {
        $rows = Import-SafeCsv -Path $filePath
        $dataStore[$map.Key] = @{
            Metadata = $map
            Rows = $rows
            Count = $rows.Count
        }
        $totalArtifactsCount += $rows.Count
        Write-Host "  [+] Ingested $($map.Title): $($rows.Count) rows" -ForegroundColor DarkGreen

        # Heuristic scan on processes & powershell history
        if ($map.Key -in @("Processes", "PSHistory", "AutoRun", "ScheduledTasks")) {
            foreach ($row in $rows) {
                $rowText = ($row.PSObject.Properties | ForEach-Object { $_.Value }) -join " "
                foreach ($pattern in $suspiciousPatterns) {
                    if ($rowText -match $pattern) {
                        $detailsText = if ($rowText.Length -gt 160) { $rowText.Substring(0, 160) + "..." } else { $rowText }
                        $suspiciousIndicators += [PSCustomObject]@{
                            Category       = $map.Category
                            Source         = $map.Title
                            PatternMatched = $pattern
                            Details        = $detailsText
                        }
                        break
                    }
                }
            }
        }
    }
}

# Determine Hostname & Date from Folder or Data
$hostname = "Unknown-Host"
$dateString = (Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC")
$folderLeaf = Split-Path $targetDir -Leaf
if ($folderLeaf -match "DFIR-([^-]+)-(\d{4}-\d{2}-\d{2})") {
    $hostname = $Matches[1]
    $dateString = $Matches[2]
} elseif ($env:COMPUTERNAME) {
    $hostname = $env:COMPUTERNAME
}

if (-not $OutputFile) {
    $OutputFile = Join-Path (Get-Location) "DFIR-Report-$hostname-$(Get-Date -Format 'yyyyMMdd_HHmmss').html"
}

# 3. Build HTML Template
Write-Host "[*] Building Interactive HTML Forensic Dashboard..." -ForegroundColor Cyan

$processCount = if ($dataStore["Processes"]) { $dataStore["Processes"].Count } else { 0 }
$tcpCount = if ($dataStore["OpenTCP"]) { $dataStore["OpenTCP"].Count } else { 0 }
$usersCount = if ($dataStore["LocalUsers"]) { $dataStore["LocalUsers"].Count } else { 0 }
$secEventsCount = if ($dataStore["SecurityEvents"]) { $dataStore["SecurityEvents"].Count } else { 0 }
$suspiciousCount = $suspiciousIndicators.Count

# Convert Data Tables to JSON for high-performance client-side rendering
$jsonDataStore = @{}
foreach ($key in $dataStore.Keys) {
    $jsonDataStore[$key] = $dataStore[$key].Rows
}
$jsonPayload = $jsonDataStore | ConvertTo-Json -Depth 5 -Compress

$suspiciousJson = $suspiciousIndicators | ConvertTo-Json -Depth 3 -Compress

$htmlBuilder = [System.Text.StringBuilder]::new()

$null = $htmlBuilder.AppendLine(@"
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>$([System.Web.HttpUtility]::HtmlEncode($Title)) - $hostname</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <style>
        :root {
            --bg-primary: #0d1117;
            --bg-secondary: #161b22;
            --bg-tertiary: #21262d;
            --border-color: #30363d;
            --text-primary: #c9d1d9;
            --text-secondary: #8b949e;
            --accent-blue: #58a6ff;
            --accent-cyan: #39c5cf;
            --accent-green: #3fb950;
            --accent-red: #f85149;
            --accent-yellow: #d29922;
            --accent-purple: #bc8cff;
            --table-hover: #1f242c;
            --card-shadow: 0 4px 20px rgba(0,0,0,0.5);
        }

        * { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; }
        body { background-color: var(--bg-primary); color: var(--text-primary); display: flex; height: 100vh; overflow: hidden; }

        /* Sidebar */
        #sidebar {
            width: 280px;
            background-color: var(--bg-secondary);
            border-right: 1px solid var(--border-color);
            display: flex;
            flex-direction: column;
            flex-shrink: 0;
        }
        .sidebar-header {
            padding: 20px;
            border-bottom: 1px solid var(--border-color);
            background: linear-gradient(135deg, rgba(88,166,255,0.1), rgba(188,140,255,0.05));
        }
        .sidebar-header h2 { font-size: 1.1rem; color: #fff; display: flex; align-items: center; gap: 10px; }
        .sidebar-header .host-badge {
            display: inline-block;
            margin-top: 8px;
            padding: 3px 8px;
            border-radius: 6px;
            font-size: 0.75rem;
            font-weight: 600;
            background: var(--bg-tertiary);
            color: var(--accent-cyan);
            border: 1px solid var(--border-color);
        }
        .sidebar-menu { list-style: none; overflow-y: auto; flex-grow: 1; padding: 10px 0; }
        .menu-category { font-size: 0.7rem; text-transform: uppercase; letter-spacing: 1px; color: var(--text-secondary); padding: 12px 20px 6px; font-weight: 700; }
        .nav-item {
            padding: 10px 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            cursor: pointer;
            font-size: 0.85rem;
            color: var(--text-primary);
            transition: all 0.15s ease;
            border-left: 3px solid transparent;
        }
        .nav-item:hover { background-color: var(--bg-tertiary); color: #fff; }
        .nav-item.active { background-color: var(--bg-tertiary); color: var(--accent-blue); border-left-color: var(--accent-blue); font-weight: 600; }
        .nav-item i { width: 20px; }
        .badge {
            font-size: 0.7rem;
            padding: 2px 6px;
            border-radius: 10px;
            background: var(--bg-primary);
            border: 1px solid var(--border-color);
            color: var(--text-secondary);
        }
        .badge-alert { background: rgba(248,81,73,0.2); color: var(--accent-red); border-color: rgba(248,81,73,0.4); font-weight: bold; }

        /* Main Content */
        #main {
            flex-grow: 1;
            display: flex;
            flex-direction: column;
            overflow: hidden;
            background-color: var(--bg-primary);
        }
        header {
            padding: 16px 28px;
            background-color: var(--bg-secondary);
            border-bottom: 1px solid var(--border-color);
            display: flex;
            align-items: center;
            justify-content: space-between;
        }
        .header-title h1 { font-size: 1.3rem; color: #fff; font-weight: 700; }
        .header-title p { font-size: 0.8rem; color: var(--text-secondary); margin-top: 2px; }
        .header-actions { display: flex; gap: 12px; align-items: center; }

        .search-box {
            position: relative;
            display: flex;
            align-items: center;
        }
        .search-box input {
            background-color: var(--bg-tertiary);
            border: 1px solid var(--border-color);
            color: #fff;
            padding: 8px 12px 8px 34px;
            border-radius: 6px;
            font-size: 0.85rem;
            width: 280px;
            outline: none;
            transition: all 0.2s ease;
        }
        .search-box input:focus { border-color: var(--accent-blue); width: 340px; box-shadow: 0 0 0 3px rgba(88,166,255,0.2); }
        .search-box i { position: absolute; left: 12px; color: var(--text-secondary); font-size: 0.85rem; }

        .content-area {
            flex-grow: 1;
            overflow-y: auto;
            padding: 24px 28px;
        }

        /* KPI Cards Grid */
        .kpi-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(210px, 1fr));
            gap: 16px;
            margin-bottom: 24px;
        }
        .kpi-card {
            background-color: var(--bg-secondary);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            padding: 16px 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
            box-shadow: var(--card-shadow);
            transition: transform 0.2s ease;
        }
        .kpi-card:hover { transform: translateY(-2px); }
        .kpi-info h3 { font-size: 0.75rem; text-transform: uppercase; color: var(--text-secondary); letter-spacing: 0.5px; }
        .kpi-info .kpi-value { font-size: 1.6rem; font-weight: 700; color: #fff; margin-top: 4px; }
        .kpi-icon {
            width: 44px;
            height: 44px;
            border-radius: 8px;
            display: flex;
            align-items: center;
            justify-content: center;
            font-size: 1.2rem;
        }
        .kpi-blue { background: rgba(88,166,255,0.15); color: var(--accent-blue); }
        .kpi-green { background: rgba(63,185,80,0.15); color: var(--accent-green); }
        .kpi-cyan { background: rgba(57,197,207,0.15); color: var(--accent-cyan); }
        .kpi-yellow { background: rgba(210,153,34,0.15); color: var(--accent-yellow); }
        .kpi-red { background: rgba(248,81,73,0.15); color: var(--accent-red); }

        /* Suspicious Alert Section */
        .alert-panel {
            background: rgba(248,81,73,0.08);
            border: 1px solid rgba(248,81,73,0.3);
            border-radius: 8px;
            padding: 16px 20px;
            margin-bottom: 24px;
        }
        .alert-panel h3 { color: var(--accent-red); font-size: 0.95rem; display: flex; align-items: center; gap: 8px; margin-bottom: 12px; }
        .alert-list { list-style: none; }
        .alert-item {
            background: var(--bg-secondary);
            border-left: 3px solid var(--accent-red);
            padding: 10px 14px;
            border-radius: 4px;
            margin-bottom: 8px;
            font-size: 0.8rem;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .alert-item code { color: #ff7b72; background: var(--bg-tertiary); padding: 2px 6px; border-radius: 4px; font-family: monospace; }

        /* Data Tables */
        .table-card {
            background-color: var(--bg-secondary);
            border: 1px solid var(--border-color);
            border-radius: 8px;
            overflow: hidden;
            box-shadow: var(--card-shadow);
        }
        .table-header {
            padding: 16px 20px;
            border-bottom: 1px solid var(--border-color);
            display: flex;
            align-items: center;
            justify-content: space-between;
            background: var(--bg-secondary);
        }
        .table-header h2 { font-size: 1rem; color: #fff; display: flex; align-items: center; gap: 10px; }
        .table-container { overflow-x: auto; max-height: calc(100vh - 280px); }
        table { width: 100%; border-collapse: collapse; text-align: left; font-size: 0.8rem; }
        thead { position: sticky; top: 0; background-color: var(--bg-tertiary); z-index: 2; }
        th {
            padding: 12px 16px;
            color: var(--text-secondary);
            font-weight: 600;
            border-bottom: 1px solid var(--border-color);
            cursor: pointer;
            user-select: none;
            white-space: nowrap;
        }
        th:hover { color: #fff; }
        th i { font-size: 0.7rem; margin-left: 4px; }
        td {
            padding: 10px 16px;
            border-bottom: 1px solid var(--border-color);
            color: var(--text-primary);
            max-width: 400px;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
        tr:hover td { background-color: var(--table-hover); }
        .suspicious-row td { background-color: rgba(248,81,73,0.06); color: #ff7b72; }

        /* Empty state */
        .empty-state { padding: 48px; text-align: center; color: var(--text-secondary); }
        .empty-state i { font-size: 2.5rem; margin-bottom: 12px; opacity: 0.5; }

        /* Scrollbar */
        ::-webkit-scrollbar { width: 8px; height: 8px; }
        ::-webkit-scrollbar-track { background: var(--bg-primary); }
        ::-webkit-scrollbar-thumb { background: var(--border-color); border-radius: 4px; }
        ::-webkit-scrollbar-thumb:hover { background: #484f58; }
    </style>
</head>
<body>

    <!-- Sidebar -->
    <div id="sidebar">
        <div class="sidebar-header">
            <h2><i class="fas fa-shield-alt" style="color: var(--accent-blue);"></i> DFIR Dashboard</h2>
            <span class="host-badge"><i class="fas fa-server"></i> $hostname</span>
        </div>
        <ul class="sidebar-menu" id="nav-list">
            <li class="menu-category">Overview</li>
            <li class="nav-item active" onclick="switchTab('overview')">
                <span><i class="fas fa-tachometer-alt"></i> Executive Summary</span>
                <span class="badge" id="badge-overview">$totalArtifactsCount</span>
            </li>
"@)

# Group navigation items by Category
$categories = @("Execution", "Network", "Persistence", "Identity", "Security", "System", "Hardware")

foreach ($cat in $categories) {
    $catItems = $dataStore.Keys | Where-Object { $dataStore[$_].Metadata.Category -eq $cat }
    if ($catItems) {
        $null = $htmlBuilder.AppendLine("            <li class='menu-category'>$cat</li>")
        foreach ($key in $catItems) {
            $item = $dataStore[$key]
            $meta = $item.Metadata
            $count = $item.Count
            $null = $htmlBuilder.AppendLine(@"
            <li class="nav-item" onclick="switchTab('$key')" id="nav-$key">
                <span><i class="$($meta.Icon)"></i> $($meta.Title)</span>
                <span class="badge">$count</span>
            </li>
"@)
        }
    }
}

$null = $htmlBuilder.AppendLine(@"
        </ul>
    </div>

    <!-- Main View Area -->
    <div id="main">
        <header>
            <div class="header-title">
                <h1 id="view-title">Executive Summary</h1>
                <p id="view-subtitle">Host: $hostname | Extraction: $dateString | Total Artifacts: $totalArtifactsCount</p>
            </div>
            <div class="header-actions">
                <div class="search-box">
                    <i class="fas fa-search"></i>
                    <input type="text" id="global-search" placeholder="Search current table..." onkeyup="filterTable()">
                </div>
            </div>
        </header>

        <div class="content-area" id="content-container">
            <!-- Overview Tab Content -->
            <div id="view-overview">
                <div class="kpi-grid">
                    <div class="kpi-card">
                        <div class="kpi-info">
                            <h3>Processes</h3>
                            <div class="kpi-value">$processCount</div>
                        </div>
                        <div class="kpi-icon kpi-blue"><i class="fas fa-microchip"></i></div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-info">
                            <h3>TCP Connections</h3>
                            <div class="kpi-value">$tcpCount</div>
                        </div>
                        <div class="kpi-icon kpi-cyan"><i class="fas fa-network-wired"></i></div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-info">
                            <h3>Local Users</h3>
                            <div class="kpi-value">$usersCount</div>
                        </div>
                        <div class="kpi-icon kpi-green"><i class="fas fa-user-shield"></i></div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-info">
                            <h3>Security Events</h3>
                            <div class="kpi-value">$secEventsCount</div>
                        </div>
                        <div class="kpi-icon kpi-yellow"><i class="fas fa-shield-alt"></i></div>
                    </div>
                    <div class="kpi-card">
                        <div class="kpi-info">
                            <h3>Suspicious Flags</h3>
                            <div class="kpi-value" style="color: var(--accent-red);">$suspiciousCount</div>
                        </div>
                        <div class="kpi-icon kpi-red"><i class="fas fa-exclamation-triangle"></i></div>
                    </div>
                </div>
"@)

if ($suspiciousCount -gt 0) {
    $null = $htmlBuilder.AppendLine(@"
                <div class="alert-panel">
                    <h3><i class="fas fa-radiation"></i> Automated Triage Alerts & Suspicious Indicators ($suspiciousCount)</h3>
                    <div class="alert-list">
"@)
    foreach ($alert in $suspiciousIndicators) {
        $srcEsc = Escape-Html $alert.Source
        $detEsc = Escape-Html $alert.Details
        $patEsc = Escape-Html $alert.PatternMatched
        $null = $htmlBuilder.AppendLine(@"
                        <div class="alert-item">
                            <div>
                                <strong>[$srcEsc]</strong> $detEsc
                            </div>
                            <code>$patEsc</code>
                        </div>
"@)
    }
    $null = $htmlBuilder.AppendLine(@"
                    </div>
                </div>
"@)
}

$null = $htmlBuilder.AppendLine(@"
                <div class="table-card">
                    <div class="table-header">
                        <h2><i class="fas fa-folder-tree"></i> Forensic Artifact Summary</h2>
                    </div>
                    <div class="table-container">
                        <table>
                            <thead>
                                <tr>
                                    <th>Category</th>
                                    <th>Artifact Description</th>
                                    <th>Source File</th>
                                    <th>Total Records</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
"@)

foreach ($key in $dataStore.Keys) {
    $item = $dataStore[$key]
    $meta = $item.Metadata
    $null = $htmlBuilder.AppendLine(@"
                                <tr>
                                    <td><span class="badge">$($meta.Category)</span></td>
                                    <td><strong>$($meta.Title)</strong></td>
                                    <td><code>$($meta.File)</code></td>
                                    <td>$($item.Count)</td>
                                    <td><button onclick="switchTab('$key')" style="padding: 4px 10px; background: var(--bg-tertiary); color: var(--accent-blue); border: 1px solid var(--border-color); border-radius: 4px; cursor: pointer;">View Table</button></td>
                                </tr>
"@)
}

$null = $htmlBuilder.AppendLine(@"
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <!-- Dynamic Table Container -->
            <div id="view-table" style="display: none;">
                <div class="table-card">
                    <div class="table-header">
                        <h2 id="current-table-title"><i class="fas fa-table"></i> Table</h2>
                        <span id="current-table-count" class="badge">0 rows</span>
                    </div>
                    <div class="table-container" id="dynamic-table-container">
                        <!-- Rendered via Javascript -->
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Data Injection & Interactive Scripts -->
    <script>
        const rawData = $jsonPayload;
        const metadata = {
"@)

foreach ($key in $dataStore.Keys) {
    $titleEsc = $dataStore[$key].Metadata.Title.Replace("'", "\'")
    $catEsc = $dataStore[$key].Metadata.Category.Replace("'", "\'")
    $null = $htmlBuilder.AppendLine("            '$key': { title: '$titleEsc', category: '$catEsc' },")
}

$null = $htmlBuilder.AppendLine(@"
        };

        let currentActiveTab = 'overview';
        let currentSortColumn = null;
        let currentSortAsc = true;
        let currentDataset = [];

        function switchTab(tabKey) {
            currentActiveTab = tabKey;

            // Update sidebar active status
            document.querySelectorAll('.nav-item').forEach(el => el.classList.remove('active'));
            const activeNav = document.getElementById('nav-' + tabKey) || document.querySelector('.nav-item');
            if (activeNav) activeNav.classList.add('active');

            const overviewView = document.getElementById('view-overview');
            const tableView = document.getElementById('view-table');
            const searchInput = document.getElementById('global-search');
            searchInput.value = '';

            if (tabKey === 'overview') {
                overviewView.style.display = 'block';
                tableView.style.display = 'none';
                document.getElementById('view-title').innerText = 'Executive Summary';
                document.getElementById('view-subtitle').innerText = 'Host: $hostname | Extraction: $dateString | Total Artifacts: $totalArtifactsCount';
            } else {
                overviewView.style.display = 'none';
                tableView.style.display = 'block';

                const meta = metadata[tabKey] || { title: tabKey, category: 'Artifact' };
                document.getElementById('view-title').innerText = meta.title;
                document.getElementById('view-subtitle').innerText = 'Category: ' + meta.category + ' | Host: $hostname';
                document.getElementById('current-table-title').innerHTML = '<i class="fas fa-table"></i> ' + meta.title;

                currentDataset = rawData[tabKey] || [];
                document.getElementById('current-table-count').innerText = currentDataset.length + ' records';

                renderTable(currentDataset);
            }
        }

        function renderTable(dataRows) {
            const container = document.getElementById('dynamic-table-container');
            if (!dataRows || dataRows.length === 0) {
                container.innerHTML = '<div class="empty-state"><i class="fas fa-inbox"></i><p>No records found for this artifact.</p></div>';
                return;
            }

            const headers = Object.keys(dataRows[0]);
            let html = '<table id="active-data-table"><thead><tr>';
            headers.forEach(h => {
                html += '<th onclick="sortTable(\'' + h + '\')">' + escapeHtml(h) + ' <i class="fas fa-sort"></i></th>';
            });
            html += '</tr></thead><tbody>';

            dataRows.forEach(row => {
                html += '<tr>';
                headers.forEach(h => {
                    const val = row[h] !== null && row[h] !== undefined ? String(row[h]) : '';
                    html += '<td title="' + escapeHtml(val) + '">' + escapeHtml(val) + '</td>';
                });
                html += '</tr>';
            });

            html += '</tbody></table>';
            container.innerHTML = html;
        }

        function filterTable() {
            if (currentActiveTab === 'overview') return;
            const query = document.getElementById('global-search').value.toLowerCase();
            if (!query) {
                renderTable(currentDataset);
                return;
            }

            const filtered = currentDataset.filter(row => {
                return Object.values(row).some(val => val && String(val).toLowerCase().includes(query));
            });

            renderTable(filtered);
            document.getElementById('current-table-count').innerText = filtered.length + ' / ' + currentDataset.length + ' records';
        }

        function sortTable(column) {
            if (currentSortColumn === column) {
                currentSortAsc = !currentSortAsc;
            } else {
                currentSortColumn = column;
                currentSortAsc = true;
            }

            currentDataset.sort((a, b) => {
                let v1 = a[column] || '';
                let v2 = b[column] || '';
                if (!isNaN(v1) && !isNaN(v2)) {
                    v1 = Number(v1);
                    v2 = Number(v2);
                }
                if (v1 < v2) return currentSortAsc ? -1 : 1;
                if (v1 > v2) return currentSortAsc ? 1 : -1;
                return 0;
            });

            renderTable(currentDataset);
        }

        function escapeHtml(str) {
            if (!str) return '';
            return String(str)
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/'/g, '&#039;');
        }
    </script>
</body>
</html>
"@)

# 4. Save HTML Report
$htmlContent = $htmlBuilder.ToString()
[System.IO.File]::WriteAllText($OutputFile, $htmlContent, [System.Text.Encoding]::UTF8)

# Cleanup temporary extract dir if created
if ($tempExtractDir -and (Test-Path $tempExtractDir)) {
    Remove-Item -Path $tempExtractDir -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host "`n===========================================================" -ForegroundColor Green
Write-Host " [+] DFIR Interactive HTML Report Successfully Generated!" -ForegroundColor Green
Write-Host " [+] Output: $OutputFile" -ForegroundColor Green
Write-Host " [+] Total records parsed: $totalArtifactsCount" -ForegroundColor Green
Write-Host "===========================================================" -ForegroundColor Green

if ($OpenReport) {
    Start-Process $OutputFile
}
